[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "19.2.0"

[[redirects]]
  from = "/contentful"
  to = "/.netlify/functions/contentful"
  status = 200
  force = true